### ISSUE TITLE
Inline JS in template files

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdata#843]
The following template files have inline JS that should be remedied. 

- [x] **[address.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/address.tmpl#L370)** -- Change QR code links to stimulus click handlers. Also page size selector `onchange` event. (#845)
- [x] **[agenda.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/agenda.tmpl#L109)** -- Inline data move to AJAX (#847)
- [x] **[charts.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/charts.tmpl#L141)** -- Inline data. Move to AJAX (#847)
- [x] **[explorer.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/explorer.tmpl#L129)** -- `onchange` event handler to stimulus (#847)
- [x] **[extras.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/extras.tmpl#L90)**  -- Inline data. Move to AJAX or websocket. (#873)
- [x] **[statistics.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/statistics.tmpl#L225)** -- Move tooltip stuff to common file. `Maybe index.js`? (#873)
- [x] **[ticketpool.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/ticketpool.tmpl#L54)** -- Inline data. Move to AJAX. (#851)
- [x] **[timelisting.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/timelisting.tmpl#L132)** -- `onchange` event handler to stimulus (#847)
- [x] **[windows.tmpl](https://github.com/decred/dcrdata/blob/4b2a5db98ef2c5e0178d7824b0361894280d22bd/views/windows.tmpl#L132)** -- `onchange` event handler to stimulus (#873)

This PR encompasses #841.

**Comment by buck54321** [comment]
To prevent duplication, let me know if you're working on or giving up on an item so that I can mark it appropriately.

**Comment by degeri** [comment]
Nice let me know once all inline are removed and deployed in alpha. I will help with making the csp rules.
